### PR TITLE
chore: update packages

### PR DESCRIPTION
**Pull request by ningsongshen**
Things to do:

- [x] take advantage of webpack v4 upgrades
- [x] streamline gruntfile and minifiers
- [ ] ~configure webpack common, prod, dev files~ (bigger change, may affect deploy, for future PR)
- [x] update setup documentation
- [x] final test to make sure everything still works fine

### CODE REVIEW

**Comment by ningsongshen** [comment]
Images, FileSafe, and general functionality don't break after these updates (from my testing).

**Comment by mobitar** [comment]
I'm having some issues with images. Can we just keep this PR as is, but remove the Redactor update? This way we can merge this in more safely. There are important changes here that have nothing to do with Redactor, so I think we can keep this more isolated, merge it in, then focus on another PR where we just update Redactor.

The issue with images I'm seeing is not consistent, but after inserting an image, then dragging it to another line (above or below some existing text), then moving to another note and coming back, the image does not appear anymore.

**Comment by ningsongshen** [comment]
Hm I thought I did keep the Redactor update in a separate PR but it looks like there are Redactor files in this one too. I'll take a look at it.

**Comment by ningsongshen** [comment]
So the Redactor version has not been changed, just minified from 9 lines to 1 line. Still at v3.1.8.

But you are right, I can occasionally produce the image dragging bug, although having a bit of trouble finding where the error could be...

**Comment by ningsongshen** [comment]
Actually, I think this might have already been an issue: https://github.com/standardnotes/bold-editor/issues/17#issuecomment-631641398

I recall that when I tested it back then, I did copy and pasting instead of dragging, but I think both have the same effect.

**Comment by mobitar** [comment]
Ah ok, I think you're right. Forgot about that issue.

**Pull request merged**
